# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EchoMail < Formula
  desc "Email Audio Reader for macOS"
  homepage "https://github.com/Agent-Hellboy/echomail"
  version "0.1.1"
  license "MIT"

  depends_on "go"
  depends_on :macos

  on_intel do
    url "https://github.com/Agent-Hellboy/echomail/releases/download/v0.1.1/echo-mail_0.1.1_darwin_amd64.tar.gz"
    sha256 "1979c1fc966a9be116188965332d80673bd2c983e2dabd4cc45e559dc10b6602"

    def install
      bin.install "echo-mail"
    end
  end
  on_arm do
    url "https://github.com/Agent-Hellboy/echomail/releases/download/v0.1.1/echo-mail_0.1.1_darwin_arm64.tar.gz"
    sha256 "0000f55e0947ff01ec8610ce9149d5eb86f4b3ad3c0d1d3591d0cef304d3937d"

    def install
      bin.install "echo-mail"
    end
  end

  test do
    system "#{bin}/echo-mail --version"
  end
end
