name: Homebrew Audit & Style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  audit-and-style:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Update Homebrew & Tap
        run: |
          brew update

      - name: Brew Audit
        run: |
          # Replace "mytool.rb" with the path or name of your formula file
          brew audit --strict ./mytool.rb

      - name: Brew Style
        run: |
          # Check Ruby style for the same formula
          brew style ./mytool.rb
